# Change these first
owner: alvarezrrj # Your GitHub organization or username, where this repository lives
repo: timba-upptime # The name of this repository

sites:
  - name: timba
    url: $TIMBA_URL
    maxResponseTime: 2500
  - name: timba-api
    url: $TIMBA_API_URL
    maxResponseTime: 2500
  - name: agent-timba
    url: $AGENT_TIMBA_URL
    maxResponseTime: 2500

assignees:
  - AlphaDev87
  - alvarezrrj

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /timba-upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAYAAABV7bNHAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABFRJREFUeNrsnMtPE0Ecx3/Q4paWPqG1CIX6AEFjlGgMCfGBj0SNRhLj0agHE2/CSY0HE096Uv8CJXo2eDPqoUajRNEEMagQaIGWVluVtnTbut3izApV46sFZ4ex802W2bLdzcxn5/f9/aZtFoCLayEqWQyduHDLY0HNMbThFmLJpO/ewEtP/8XTvqIHhOB02Gyma5rSUks4MpX7fzgeg2cjI1d6L3R10eyfhjIcd22N/YnbXa0TxRTE4mLumEEQwGIwtKabNpS8e3TfQ6uPpZQn0Hmn0waBQBi84yF4HQjAWCScO2g3msBqMJyi2UHagDYMvh6DYOgjPBkegsGA/3rf6Gh7SpJ65t5QaTRa1p+55KbVQS1tQDi0sKKiOIVM+TjeP3TLczAXaksE3GBAvqIChPyn8/vXrQ0NlgPIkzC02YymqN5uhw/T8YP9AFR8qKAsdvfsVpyG8cC2FXJestwB3vr9EDPmIsU9u/1Wer0OtNpvOQTtezIZGWKxBJSMPAbp7QMQxA/KMaNOA01Lhb/2IxaVpxJx+fbRG73XSc2g87OA8pa/ph38y9oBZSuotxqVgc9T2/GfdFqCIXSNRO1GiPT1QE3wWd4XMJk1IH2e6eg+0roeQcqrfCjUpAuCE65qUeA0NrigBgFaAJycBKEM1jTXgx6VAaZNHeCzNhd4vhI0nQiSm7oHjdXt/Ta9v6txFioZhZoShgjSZOMOkAa887lMXsa/YEDG6lWw6cRV0OoqfoSDquLeh/3K/tDwBLGbYLZUwsye07D70P6fjvXfPAfvBx/RrYMca7b8BEdteaO/np11bYeZLxT/iVJylr1KWs7KIMkycTjRhIjSvEDs+sRMeoWjEpZZBegbnSAKqAyN4OSuNjYr6ZM7Ucd3sh2+/4UHcUAcEAfErIiYtJTJwHgoDBnUqiWX0wF6AumeCKBRfxDeeCdUvdNiMg0tzavYALSithoqLWZVAekJFYtEAJVptVBlMXGT5lmMiwOi4kHByEd4OvBG1YE0LXfBareLncVqlcpZrJylLFZdZVM27kHcpLk4IBoeJKbSMBF6r+pAnMjzzBUGdtK82ovVaDwBm9c1sQFoJVqskribf5K5Qs9OiH2tg/hilWcxLg6IjgeN+IPwatir6kDqnA52PnLFBq32YtVpt7Ezg3CKb2tZyz2ImzQXB0TFg6LTCXiL1mJSRlZtIKuXu4hU70QARaZiyoJVTemDAjuA8GIVb9yDuElzcUA0PGjOqAsyWZ1A7Bca/8ViFf8iZN+WzcUBCKdb/FVwQR3RaosnxPBiVe3PpLlJc0AcUHECSn4KLtrBJT+F6Jv05Is7SltuXVxrLykVh8nndxZHFpuDVPQhJsszzA84myUIKDGd7WEZjiTNQFKUyYVYIi53p5LZDo2mhElAn9M/TB9fPucUPNLuI63HUHMZZp8WxaDwU5y68n08xbynAgK1nUU6CIyHV3dc6umLAAMAu9VHyS9rQ8gAAAAASUVORK5CYII=
  name: Timba upptime
  introTitle: Timba uptime monitor
  introMessage: Hola
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
