# This is a scheduled workflow to check the health of banxico's transfer checker

name: Banxico Monitor

# Controls when the workflow will run
on:
  # Runs every 5 minutes
  schedule:
    - cron: "*/5 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_banxico:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: Create initial artifact
      #   run: echo 1 > banxico-status.txt
      # - name: Upload initial artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: banxico-status
      #     path: banxico-status.txt
          
      - name: Download state artifact
        uses: actions/download-artifact@v4
        with:
          name: banxico-status
          path: prev
          # github-token: ${{ secrets.GH_PAT }}
          # run-id: 
          
      - name: Send form and store cookie as env variable
        run: |
          echo COOKIE=$(curl -X POST -i https://www.banxico.org.mx/cep/valida.do \
          -d 'tipoCriterio=T&fecha=11-03-2024&criterio=53771ALBO11032024195558814&emisor=90646&receptor=90659&cuenta=659437001005389354&receptorParticipante=0&monto=10&captcha=c&tipoConsulta=1' \
          | grep JSESSIONID \
          | sed 's/Set-Cookie: //' \
          | sed 's/;.*//') >> $GITHUB_ENV
          
      - name: Download xml
        run: |
          curl https://www.banxico.org.mx/cep/descarga.do?formato=XML -H "Cookie: $COOKIE" | grep 'MontoPago="10.00"' > log.txt
          
      - name: Store banxico status
        run: |
          if [ -s log.txt ]; then echo "1" > banxico-status.txt; else echo "0" > banxico-status.txt; fi
          echo CURRENT_STATUS=$(cat banxico-status.txt) >> $GITHUB_ENV

          
      - name: Check status against prev state
        run: |
          if [ "$(cat banxico-status.txt)" = "$(cat prev/banxico-status.txt)" ]; then
            echo NOTIFY=0 >> $GITHUB_ENV
          else
            echo NOTIFY=1 >> $GITHUB_ENV
          fi

      - name: Notify
        run: |
          if (( NOTIFY == 1 )); then
            if (( CURRENT_STATUS == 0 )); then
              MESSAGE="游린 Banxico est치 rompido"
            elif (( CURRENT_STATUS == 1 )); then
              MESSAGE="游릴 Banxico volvi칩 al ruedo"
            fi

            curl https://api.telegram.org/bot${{ secrets.NOTIFICATION_TELEGRAM_BOT_KEY }}/sendMessage \
            -d text="$MESSAGE" \
            -d chat_id=${{ secrets.NOTIFICATION_TELEGRAM_CHAT_ID }}
          fi

      - name: Store state artifact
        uses: actions/upload-artifact@v4
        with:
          name: banxico-status
          path: banxico-status.txt
            
          
        
